apiVersion: crd.xzbc.com.cn/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster01
spec:
  # Add fields here
  replicas: 6
  image: redis
  redistribimage: redis-trib:1.0
  redistribscaleimage: redis-trib-scale:1.0
  storage: 5Gi
  storageClassName: nfs
