apiVersion: apps/v1
kind: Deployment
metadata:
  name: xzbc-redis-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: xzbc-redis-cluster
  template:
    metadata:
      labels:
        name: xzbc-redis-cluster
    spec:
      serviceAccountName: xzbc-redis-cluster
      containers:
        - name: xzbc-redis-cluster
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - xzbc-redis-cluster
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "xzbc-redis-cluster"
